### ISSUE TITLE
哥哥有API使用文档吗？

### ISSUE THREAD

**Issue by Morikernel** [hanximeng/BOT_API#5]
如上

**Comment by hanximeng** [comment]
加QQ群吧，549522943

**Comment by Sunshine214000** [comment]
好的 多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hanximeng/BOT_API"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月20日(星期六) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hanximeng/BOT_API] 哥哥有API使用文档吗？ (Issue #5)





 
加QQ群吧，549522943
